#!/usr/bin/bash

# ############################################################################ #
#                                                                              #
#   Copyleft (C) 2020-2023, Marek Gagolewski <https://www.gagolewski.com>      #
#                                                                              #
#                                                                              #
#   This program is free software: you can redistribute it and/or modify       #
#   it under the terms of the GNU Affero General Public License                #
#   Version 3, 19 November 2007, published by the Free Software Foundation.    #
#   This program is distributed in the hope that it will be useful,            #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
#   GNU Affero General Public License Version 3 for more details.              #
#   You should have received a copy of the License along with this program.    #
#   If this is not the case, refer to <https://www.gnu.org/licenses/>.         #
#                                                                              #
# ############################################################################ #

set -e

if [ ! -f "${1}" ]; then
    echo "clipimg2base64 Copyleft (C) 2023, Marek Gagolewski <https://www.gagolewski.com>"
    echo "input file does not exist or no input provided"
    echo "usage: clipimg2base64 infile"
    exit 1
fi

base64 --wrap=0 "${1}" | \
printf 'data:image/png;base64,%s\n' "$(cat)" | \
fold -b --width=4080 | \
sed 's/$/\\/' | \
xclip -i -selection clipboard
