#!/usr/bin/bash
# kate: syntax bash

# ############################################################################ #
#                                                                              #
#   Copyleft (C) 2020-2021, Marek Gagolewski <https://www.gagolewski.com>      #
#                                                                              #
#                                                                              #
#   This program is free software: you can redistribute it and/or modify       #
#   it under the terms of the GNU Affero General Public License                #
#   Version 3, 19 November 2007, published by the Free Software Foundation.    #
#   This program is distributed in the hope that it will be useful,            #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
#   GNU Affero General Public License Version 3 for more details.              #
#   You should have received a copy of the License along with this program.    #
#   If this is not the case, refer to <https://www.gnu.org/licenses/>.         #
#                                                                              #
# ############################################################################ #

# colourised find+grep displaying full URIs and excluding file paths
# listed in ./.grepexclude (unless [path] is given)

# Usage: grep2 [path] -FLAGSe expression

if [ $# -eq 2 ]; then
    set -o noglob
    exclude_paths=`[ -f .grepexclude ] && cat .grepexclude`
    exclude_args=''
    for f in ${exclude_paths[@]}; do
        exclude_args="${exclude_args} -not -path ./${f}"
    done
    files=`echo $exclude_args | xargs find -type f | sort`
    set +o noglob

    echo $files | xargs grep --color=always -T $@  | sed -r -e "s|./|file://`pwd`/|"
elif [ $# -eq 3 ]; then
    path=`readlink -f $1`
    files=`find $path -type f | sort`

    echo $files | xargs grep --color=always -T $2 $3  | sed -r -e "s|/|file:///|"
else
    echo "Usage: $0 [path] -flags pattern  (e.g., man/ -FIine 'query')"
    exit 1
fi


