#!/bin/bash

# ############################################################################ #
#                                                                              #
#   Copyleft (C) 2020-2021, Marek Gagolewski <https://www.gagolewski.com>      #
#                                                                              #
#                                                                              #
#   This program is free software: you can redistribute it and/or modify       #
#   it under the terms of the GNU Affero General Public License                #
#   Version 3, 19 November 2007, published by the Free Software Foundation.    #
#   This program is distributed in the hope that it will be useful,            #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
#   GNU Affero General Public License Version 3 for more details.              #
#   You should have received a copy of the License along with this program.    #
#   If this is not the case, refer to <https://www.gnu.org/licenses/>.         #
#                                                                              #
# ############################################################################ #


set -e

if [ ! -f "${1}" ]; then
    echo "knit2html Copyleft (C) 2020-2021, Marek Gagolewski <https://www.gagolewski.com>"
    echo "input file does not exist or no input provided"
    echo "usage: knit2html infile [outfile]"
    exit 1
fi

keepsources=false


if [ -z "${2}" ]; then
    outfile="${1/%.Rmd/.html}"
else
    outfile="${2}"
fi
tmpdir="tmp-html-${1/%.Rmd/}"
knitrfile="tmp-html-${1/%.Rmd/}.Rmd"
mdfile="tmp-html-${1/%.Rmd/}.md"

#rm -f "${outfile}"
rm -f "${mdfile}"

echo "${0}: converting ${1} → ${outfile}"

# mimeinput=`mimetype -b "${1}"`
# if [ $mimeinput == "text/x-r-markdown" ]; then
mkdir -p "${tmpdir}"
rm -f "${knitrfile}"

echo "\`\`\`{r,echo=FALSE}" > "${knitrfile}"
cat /home/gagolews/bin/knit2html-options.R >> "${knitrfile}"
echo "\`\`\`" >> "${knitrfile}"
echo "" >> "${knitrfile}"
cat "${1}" >> "${knitrfile}"
#sed -e 's@^---$@<p></p>@g' "${1}" >> "${knitrfile}"


Rscript -e "\
    library('knitr');                              \
    opts_knit\$set(progress=FALSE, verbose=TRUE); \
    opts_chunk\$set(                               \
        cache.path='${tmpdir}/cache/',    \
        fig.path='${tmpdir}/figures/'     \
    );                                             \
    knit('${knitrfile}', '${mdfile}')
"
# else
#     cp "${1}" "${mdfile}"
# fi


# else: text/markdown

if [ -z "${MATHJAX_URL+x}" ]; then
    MATHJAX_URL="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
fi


echo "Using MATHJAX_URL=${MATHJAX_URL}"

pandoc +RTS -K512m -RTS \
    "${mdfile}" \
    --output "${outfile}" \
    --from markdown+autolink_bare_uris+tex_math_single_backslash+tex_math_dollars+smart-implicit_figures \
    --to html5 \
    --template /home/gagolews/bin/knit2html-template.html \
    --highlight-style tango \
    --variable "theme:flatly" \
    --variable "mathjax-url:${MATHJAX_URL}" \
    --email-obfuscation none \
    --number-sections \
    --self-contained \
    --standalone \
    --section-divs \
    --table-of-contents \
    --toc-depth 2 \
    --top-level-division=section \
    --mathjax
    #--default-image-extension .svg \


if [ "$keepsources" == false ]; then
    rm -f "${knitrfile}"
    rm -f "${mdfile}"
    rm -rf "${tmpdir}"

#         if [ -z "$(ls -A ${tmpdir})" ]; then
#             # if tmpdir empty
#             rmdir "$tmpdir"
#         fi
fi
