#!/bin/bash

# ############################################################################ #
#                                                                              #
#   Copyleft (C) 2020, Marek Gagolewski <https://www.gagolewski.com>           #
#                                                                              #
#                                                                              #
#   This program is free software: you can redistribute it and/or modify       #
#   it under the terms of the GNU Affero General Public License                #
#   Version 3, 19 November 2007, published by the Free Software Foundation.    #
#   This program is distributed in the hope that it will be useful,            #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
#   GNU Affero General Public License Version 3 for more details.              #
#   You should have received a copy of the License along with this program.    #
#   If this is not the case, refer to <https://www.gnu.org/licenses/>.         #
#                                                                              #
# ############################################################################ #


set -e

if [ ! -f "${1}" ]; then
    echo "knit2md Copyleft (C) 2020, Marek Gagolewski <https://www.gagolewski.com>"
    echo "input file does not exist or no input provided"
    echo "usage: knit2md infile [outfile]"
    exit 1
fi

keepsources=false

mimeinput=`mimetype -b "${1}"`

if [ $mimeinput == "text/x-r-markdown" ]; then
    figuresdir="${1/%.Rmd/}-figures"

    knitrfile="${1/%.Rmd/}-tmp-md.Rmd"
    mdfile="${1/%.Rmd/}-tmp-md.md"

    if [ -z "${2}" ]; then
        outfile="${1/%.Rmd/.md}"
    else
        outfile="${2}"
    fi


    echo "Compiling ${1} → ${outfile}..."

    rm -f "${knitrfile}"
    rm -f "${mdfile}"
    #rm -f "${outfile}"
    mkdir -p "${figuresdir}"
    rm -f "{$figuresdir}/*"


    echo "\`\`\`{r,echo=FALSE}" > "${knitrfile}"
    cat /home/gagolews/bin/knit2md-options.R >> "${knitrfile}"
    echo "\`\`\`" >> "${knitrfile}"
    echo "" >> "${knitrfile}"
    cat "${1}" >> "${knitrfile}"
    #sed -e 's@^---$@<p></p>@g' "${1}" >> "${knitrfile}"


    Rscript --vanilla -e "\
        library('knitr');                              \
        opts_knit\$set(progress=FALSE, verbose=TRUE); \
        opts_chunk\$set(
            fig.path='${figuresdir}/'     \
        );                                             \
        knit('${knitrfile}', '${mdfile}')
    "
else
    exit 1
fi



# strip pwd from image paths like ](....
Rscript --vanilla -e "\
    library('stringi'); \
    f <- stri_replace_first_fixed(readLines('${mdfile}'), '](`pwd`/', ']('); \
    writeLines(f, '${outfile}');
"


rm -f "${knitrfile}"
rm -f "${mdfile}"

echo "Finished compiling ${1} → ${outfile}. OK."
