#!/bin/bash
# kate: hl bash

# ############################################################################ #
#                                                                              #
#   Copyleft (C) 2022-2023, Marek Gagolewski <https://www.gagolewski.com>           #
#                                                                              #
#                                                                              #
#   This program is free software: you can redistribute it and/or modify       #
#   it under the terms of the GNU Affero General Public License                #
#   Version 3, 19 November 2007, published by the Free Software Foundation.    #
#   This program is distributed in the hope that it will be useful,            #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
#   GNU Affero General Public License Version 3 for more details.              #
#   You should have received a copy of the License along with this program.    #
#   If this is not the case, refer to <https://www.gnu.org/licenses/>.         #
#                                                                              #
# ############################################################################ #


dpi=1200
tmpdir=/tmp/latexmk-prepress
origdir=`pwd`

set -e

if [ ! -d "${1}" -o -z "${2}" ]; then
    echo "latexmk-prepress Copyleft (C) 2022-2023, Marek Gagolewski <https://www.gagolewski.com>"
    echo "input directory does not exist, no directory provided, or no output file provided"
    echo "usage: ${0} indir outfile"
    exit 1
fi



rm -rf "${tmpdir}"
mkdir -p "${tmpdir}"
cp "${1}"/* "${tmpdir}"
cd "${tmpdir}"
make clean

TEXFILE=`basename *.tex`
PDFFILE="${TEXFILE/%.tex/.pdf}"

for f in *.pdf; do
    echo "*** converting (rasterising, grey-scaling) ${f}..."
    # antialias best -> bug? does not render text correctly :/
    # pdftocairo supports rasterising semi-transparent streams, pdftops does not
    pdftocairo "$f" -antialias good -r $dpi -origpagesizes -level2 -ps .out.ps
    gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite \
        -r1200  -dCompatibilityLevel=1.5 -dPDFSETTINGS=/prepress  \
        -dEmbedAllFonts=true -dSubsetFonts=true -dCompressFonts=true \
        -dDetectDuplicateImages  \
        -dColorImageResolution=$dpi -dAntiAliasColorImages=true \
        -dGrayImageResolution=$dpi  -dAntiAliasGrayImages=true  \
        -dMonoImageResolution=$dpi  -dAntiAliasMonoImages=true  \
        -dAutoRotatePages=/All  \
        -dProcessColorModel=/DeviceGray -sColorConversionStrategy=Gray \
        -dCompressPages=true \
        -sOutputFile="$f" .out.ps
    rm -f .out.ps
done


echo "*** running latexmk..."

latexmk -quiet -pdfxe -dvi- -ps-  # should create $PDFFILE


echo "*** generating print-ready PDF..."

cd "${origdir}"

gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite \
        -r1200  -dCompatibilityLevel=1.5 -dPDFSETTINGS=/prepress  \
        -dEmbedAllFonts=true -dSubsetFonts=true -dCompressFonts=true \
        -dDetectDuplicateImages  \
        -dColorImageResolution=$dpi -dAntiAliasColorImages=true \
        -dGrayImageResolution=$dpi  -dAntiAliasGrayImages=true  \
        -dMonoImageResolution=$dpi  -dAntiAliasMonoImages=true  \
        -dAutoRotatePages=/All  \
        -dProcessColorModel=/DeviceGray -sColorConversionStrategy=Gray \
        -dCompressPages=true \
        -sOutputFile="${2}" "${tmpdir}/${PDFFILE}"

echo "*** output saved as ${2} ✅✅✅"
