#!/usr/bin/python3

"""
Preview a HTML file and watch it for changes.

# ############################################################################ #
#                                                                              #
#   Copyleft (C) 2020-2022, Marek Gagolewski <https://www.gagolewski.com>      #
#                                                                              #
#                                                                              #
#   This program is free software: you can redistribute it and/or modify       #
#   it under the terms of the GNU Affero General Public License                #
#   Version 3, 19 November 2007, published by the Free Software Foundation.    #
#   This program is distributed in the hope that it will be useful,            #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
#   GNU Affero General Public License Version 3 for more details.              #
#   You should have received a copy of the License along with this program.    #
#   If this is not the case, refer to <https://www.gnu.org/licenses/>.         #
#                                                                              #
# ############################################################################ #
"""


import PySide2
import sys, os.path, tempfile, os, subprocess, hashlib
from PySide2.QtWidgets import QVBoxLayout, QApplication
from PySide2.QtWidgets import QWidget, QTextEdit, QSplitter
from PySide2.QtCore import QFileSystemWatcher, QUrl
from PySide2.QtWebEngineWidgets import QWebEngineView, QWebEngineSettings
import time

import argparse


class MainWindow(QWidget):
    def __init__(self, filename):
        super().__init__()
        self.filename = filename
        self.setWindowTitle(self.filename)
        self.htmlview = QWebEngineView()

        screen = app.screenAt(self.pos())
        size = screen.availableGeometry()
        self.resize(size.width()//3, size.height())
        self.move(2*size.width()//3,0)

        layout = QVBoxLayout(self)
        layout.addWidget(self.htmlview)
        self.setLayout(layout)
        self.lasthash = ""


    def refresh(self): # this is sometimes called twice, hence we use a hashfun
        #self.htmlview.setHtml("""
            #<html><body>
            #<h1 style='color:gray'>Building %s...</h1>
            #</body></html>
        #"""%self.filename)
        global watcher

        while not os.path.isfile(self.filename):
            time.sleep(0.1)

        if self.filename not in watcher.files():
            # the file might be deleted and then recreated
            watcher.addPath(self.filename)



        h = hashlib.sha1()
        with open(self.filename, "rb") as f:
            buf = f.read()
            h.update(buf)

        if self.lasthash == h.hexdigest():
            return # nothing to do, file not changed
        else:
            self.lasthash = h.hexdigest()

        self.htmlview.setUrl(QUrl.fromLocalFile(self.filename))
        self.htmlview.page().settings().setAttribute(
            QWebEngineSettings.LocalContentCanAccessRemoteUrls,
            True
        )  # e.g., allow externally hosted MathJax


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='Preview a HTML file and watch it for changes.',
        epilog='Copyleft (C) 2020-2022, Marek Gagolewski <https://www.gagolewski.com>'
    )
    parser.add_argument("filename")
    args = parser.parse_args()

    if not os.path.isfile(args.filename):
        print("File %s does not exist."%args.filename, file=sys.stderr)
        sys.exit(1)


    app = QApplication(sys.argv)
    main = MainWindow(os.path.abspath(args.filename))

    watcher = QFileSystemWatcher([os.path.abspath(args.filename)])
    watcher.fileChanged.connect(main.refresh)
    main.refresh()

    main.show()
    app.exec_()

