#!/bin/bash

# ############################################################################ #
#                                                                              #
#   Copyleft (C) 2020-2021, Marek Gagolewski <https://www.gagolewski.com>      #
#                                                                              #
#                                                                              #
#   This program is free software: you can redistribute it and/or modify       #
#   it under the terms of the GNU Affero General Public License                #
#   Version 3, 19 November 2007, published by the Free Software Foundation.    #
#   This program is distributed in the hope that it will be useful,            #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
#   GNU Affero General Public License Version 3 for more details.              #
#   You should have received a copy of the License along with this program.    #
#   If this is not the case, refer to <https://www.gnu.org/licenses/>.         #
#                                                                              #
# ############################################################################ #

set +e

if [ ! -f "${1}" ]; then
    echo "video2mp3"
    echo "input file does not exist or no input provided"
    echo "usage: video2mp3 infile [outfile]"
    exit 1
fi

if [ -z "${2}" ]; then
    outfile="${1}.mp3" # you can rename the file manually thereafter
else
    outfile="${2}"
fi

ffmpeg -i "${1}" -codec:a libmp3lame -qscale:a 2 "${outfile}"
